# Generated by Django 6.0.6 on 2026-06-05 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_tag_libro_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
