# Generated by Django 6.0.6 on 2026-06-06 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_remove_libro_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.autor'),
        ),
    ]
