# Generated by Django 6.0.6 on 2026-06-09 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_tag_alter_libro_genero_libro_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='genero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.genero'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='libros', to='biblioteca.tag'),
        ),
    ]
