# Generated by Django 6.0.6 on 2026-06-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_alter_libro_genero_alter_libro_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=100)),
                ('anio_fundacion', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Editoriales',
            },
        ),
    ]
