# Generated by Django 6.0.6 on 2026-06-11 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_editorial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='fecha_publicacion',
            field=models.DateField(default='2000-01-01'),
        ),
    ]
