# Generated by Django 6.0.6 on 2026-06-11 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_libro_fecha_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='fecha_publicacion',
            new_name='publication_date',
        ),
    ]
