# Generated by Django 6.0.6 on 2026-06-11 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0010_rename_fecha_publicacion_libro_publication_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='publication_date',
            field=models.DateField(),
        ),
    ]
