# Generated by Django 6.0.6 on 2026-06-11 23:38

from django.db import migrations


GENEROS = [
    'Novela', 'Cuento', 'Poesía',
    'Ensayo', 'Teatro', 'Crónica',
]

def poblar_generos(apps, schema_editor):
    Genero = apps.get_model('biblioteca', 'Genero')
    for nombre in GENEROS:
        Genero.objects.get_or_create(nombre=nombre)


def revertir_generos(apps, schema_editor):

    Genero = apps.get_model('biblioteca', 'Genero')

    Genero.objects.filter(nombre__in=GENEROS).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_alter_libro_publication_date'),
    ]

    operations = [
            migrations.RunPython(poblar_generos, revertir_generos),
    ]


