# Generated by Django 6.0.6 on 2026-06-12 00:49

from django.db import migrations

AUTORES = [
    ('Gabriel', 'García Márquez', 'Colombiana'),
    ('Pablo', 'Neruda', 'Chilena'),
    ('Jorge Luis', 'Borges', 'Argentina')
]

def poblar_autores(apps, schema_editor):
    Autor = apps.get_model('biblioteca', 'Autor')
    for nombre, apellido, nacionalidad in AUTORES:
        Autor.objects.get_or_create(nombre=nombre, apellido=apellido, nacionalidad=nacionalidad)
    
def revertir_autores(apps, schema_editor):
    Autor = apps.get_model('biblioteca', 'Autor')
    for nombre, apellido, nacionalidad in AUTORES:
        Autor.objects.filter(nombre=nombre, apellido=apellido, nacionalidad=nacionalidad).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_poblar_generos'),
    ]

    operations = [
        migrations.RunPython(poblar_autores, revertir_autores),
    ]
