# Generated by Django 6.0.6 on 2026-06-12 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_poblar_autores'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revista',
            name='autor',
        ),
        migrations.AddField(
            model_name='prestamo',
            name='revista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.revista'),
        ),
        migrations.AddField(
            model_name='revista',
            name='editorial_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.editorial'),
        ),
    ]
