# Generated by Django 6.0.6 on 2026-06-13 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_alter_prestamo_libro'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
