# Generated by Django 6.0.6 on 2026-06-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_libro_paginas'),
    ]

    operations = [
        migrations.AddField(
            model_name='revista',
            name='paginas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revista',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='revistas', to='biblioteca.tag'),
        ),
    ]
