# Generated by Django 6.0.6 on 2026-06-04 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='telefono',
        ),
        migrations.AddField(
            model_name='customuser',
            name='phono',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
