# Generated by Django 6.0.6 on 2026-06-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_customuser_telefono_customuser_phono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='phono',
            new_name='phone',
        ),
    ]
